{
    "_meta": {
        "retrieved_2nd_on": 1712907810
    },
    "all_awardings": [],
    "allow_live_comments": false,
    "approved_at_utc": null,
    "approved_by": null,
    "archived": false,
    "author": "SamLoser2",
    "author_flair_background_color": null,
    "author_flair_css_class": null,
    "author_flair_richtext": [],
    "author_flair_template_id": null,
    "author_flair_text": null,
    "author_flair_text_color": null,
    "author_flair_type": "text",
    "author_fullname": "t2_trexk6mc",
    "author_is_blocked": false,
    "author_patreon_flair": false,
    "author_premium": false,
    "awarders": [],
    "banned_at_utc": null,
    "banned_by": null,
    "can_gild": false,
    "can_mod_post": false,
    "category": null,
    "clicked": false,
    "content_categories": null,
    "contest_mode": false,
    "created": 1712778197,
    "created_utc": 1712778197,
    "discussion_type": null,
    "distinguished": null,
    "domain": "self.ChatGPT",
    "downs": 0,
    "edited": false,
    "gilded": 0,
    "gildings": {},
    "hidden": false,
    "hide_score": false,
    "id": "1c0ujjt",
    "is_created_from_ads_ui": false,
    "is_crosspostable": true,
    "is_meta": false,
    "is_original_content": false,
    "is_reddit_media_domain": false,
    "is_robot_indexable": true,
    "is_self": true,
    "is_video": false,
    "likes": null,
    "link_flair_background_color": "#94e044",
    "link_flair_css_class": "",
    "link_flair_richtext": [
        {
            "e": "text",
            "t": "Other "
        }
    ],
    "link_flair_template_id": "b4536a20-7be9-11ed-9a10-deed22fd00f8",
    "link_flair_text": "Other ",
    "link_flair_text_color": "light",
    "link_flair_type": "richtext",
    "locked": false,
    "media": null,
    "media_embed": {},
    "media_only": false,
    "mod_note": null,
    "mod_reason_by": null,
    "mod_reason_title": null,
    "mod_reports": [],
    "name": "t3_1c0ujjt",
    "no_follow": true,
    "num_comments": 8,
    "num_crossposts": 0,
    "num_reports": null,
    "over_18": false,
    "parent_whitelist_status": "all_ads",
    "permalink": "/r/ChatGPT/comments/1c0ujjt/youve_reached_the_current_usage_cap_for_gpt4_but/",
    "pinned": false,
    "pwls": 6,
    "quarantine": false,
    "removal_reason": null,
    "removed_by": null,
    "removed_by_category": null,
    "report_reasons": null,
    "retrieved_on": 1712778215,
    "saved": false,
    "score": 14,
    "secure_media": null,
    "secure_media_embed": {},
    "selftext": "\"\"You've reached the current usage cap for GPT-4. You can continue with the default model now, or try again later. Learn more\"\n\nI got this message after using GPT for a number of things. Only I am not using GPT-4, I only have the free plan and have been exclusively using GPT-3.5. Clicking \"use default model\" does nothing.  \n\n\nIf there is a throttle for GPT-3.5 on free plans I didn't know about then that sucks but I totally get it. I only ask that you give me a proper error message so I don't get completely confused with the wrong information. Does anyone know if that is the reason for this message? Has anyone else experienced an incorrect error message like this?",
    "send_replies": true,
    "spoiler": false,
    "stickied": false,
    "subreddit": "ChatGPT",
    "subreddit_id": "t5_7hqomg",
    "subreddit_name_prefixed": "r/ChatGPT",
    "subreddit_subscribers": 5033578,
    "subreddit_type": "public",
    "suggested_sort": null,
    "thumbnail": "self",
    "thumbnail_height": null,
    "thumbnail_width": null,
    "title": "\"You've reached the current usage cap for GPT-4.\" ..but I'm not using GPT-4?",
    "top_awarded_type": null,
    "total_awards_received": 0,
    "treatment_tags": [],
    "ups": 14,
    "upvote_ratio": 0.7599999904632568,
    "url": "https://www.reddit.com/r/ChatGPT/comments/1c0ujjt/youve_reached_the_current_usage_cap_for_gpt4_but/",
    "user_reports": [],
    "view_count": null,
    "visited": false,
    "whitelist_status": "all_ads",
    "wls": 6
}